### ISSUE TITLE
callout功能 以及highlight,inline-math

### ISSUE THREAD

**Issue by AsleepX** [Jambo2018/notion-assistant-plugin#10]
希望可以添加/键唤出callout语法，感谢作者！

**Comment by AsleepX** [comment]
[typing-assistant.zip](https://github.com/Jambo2018/notion-assistant-plugin/files/13432769/typing-assistant.zip)

**Comment by moxiaonai** [comment]
> [typing-assistant.zip](https://github.com/Jambo2018/notion-assistant-plugin/files/13432769/typing-assistant.zip) 我自己修改了一下，添加了 / 键唤出 Callout Note,Summary 功能，以及选中文字修改为inline math。

挺好用的，可以提个pull request

**Comment by AsleepX** [comment]
> > [typing-assistant.zip](https://github.com/Jambo2018/notion-assistant-plugin/files/13432769/typing-assistant.zip) 我自己修改了一下，添加了 / 键唤出 Callout Note,Summary 功能，以及选中文字修改为inline math。
> 
> 挺好用的，可以提个pull request

不太会（）

**Comment by moxiaonai** [comment]
> > > [typing-assistant.zip](https://github.com/Jambo2018/notion-assistant-plugin/files/13432769/typing-assistant.zip) 我自己修改了一下，添加了 / 键唤出 Callout Note,Summary 功能，以及选中文字修改为inline math。
> > 
> > 
> > 挺好用的，可以提个pull request
> 
> 不太会（）
fork -> clone -> 切feature分支 ->  添加改动，注意一下代码质量 -> push 到远端 -> Compare & pull request
可以参考
https://www.freecodecamp.org/chinese/news/how-to-make-your-first-pull-request-on-github/

**Comment by AsleepX** [comment]
弄不来呜呜呜，太笨力

**Comment by AsleepX** [comment]
> > > > [typing-assistant.zip](https://github.com/Jambo2018/notion-assistant-plugin/files/13432769/typing-assistant.zip) 我自己修改了一下，添加了 / 键唤出 Callout Note,Summary 功能，以及选中文字修改为inline math。
> > > 
> > > 
> > > 挺好用的，可以提个pull request
> > 
> > 
> > 不太会（）
> > fork -> clone -> 切feature分支 ->  添加改动，注意一下代码质量 -> push 到远端 -> Compare & pull request
> > 可以参考
> > https://www.freecodecamp.org/chinese/news/how-to-make-your-first-pull-request-on-github/

谢谢你这么耐心地指导，但是我下载完git后遇到了一些问题。弄不来了。。。

**Comment by Jambo2018** [comment]
感谢感谢🙏
