### ISSUE TITLE
升级到0.2.6-beta.0查找bug

### ISSUE THREAD

**Issue by mzihen** [Jambo2018/notion-assistant-plugin#19]
升级到0.2.6-beta.0，文档在编辑模式下，使用当前文章中的查找功能，光标无法定位到查找框里，会定位到之前查找之前文档中的位置，此时输入文字也是在之前文档里插入文字。
![Snipaste20240407141315](https://github.com/Jambo2018/notion-assistant-plugin/assets/5365531/aee49892-fce6-41e8-8ed1-e49c17e4e761)

希望能优化一下。

最后非常感谢开发这么棒的插件。

**Comment by Jambo2018** [comment]
再试试看[0.2.6-beta.1](https://github.com/Jambo2018/notion-assistant-plugin/releases/tag/0.2.6-beta.1)🤣

**Comment by mzihen** [comment]
> 再试试看[0.2.6-beta.1](https://github.com/Jambo2018/notion-assistant-plugin/releases/tag/0.2.6-beta.1)🤣

现在好了，谢谢，辛苦了！
