### ISSUE TITLE
It seems to have affected some page appearances

### ISSUE THREAD

**Issue by i-iooi-i** [Jambo2018/notion-assistant-plugin#2]
I really like this plugin, it feels very friendly. But I also found some small problems, maybe not the problem. 😂

![image](https://github.com/Jambo2018/notion-assistant-plugin/assets/1827701/b50ff6fb-7d18-416c-a368-cd5587e61160)
Open plugin

![image](https://github.com/Jambo2018/notion-assistant-plugin/assets/1827701/a6561794-4c5b-4989-a888-06787e1a98a3)
Close plugin

At first, I thought there was a problem with the theme, but when I switched to other themes and found the same problem, it seemed to affect all the themes, Can you consider adding a feature and turning it off. Thank you very much~

**Comment by Jambo2018** [comment]
Which theme plugin are you using now

**Comment by i-iooi-i** [comment]
> Which theme plugin are you using now

![image](https://github.com/Jambo2018/notion-assistant-plugin/assets/1827701/24e4da71-d84b-450a-8f9c-ecf7e99c016e)

When using the default theme, this bookmark page will be affected.

**Comment by i-iooi-i** [comment]
> Which theme plugin are you using now

![image](https://github.com/Jambo2018/notion-assistant-plugin/assets/1827701/5f523cce-ea1c-458e-9bff-3a0f68654dc5)
When using other themes, for example https://github.com/Bluemoondragon07/chime-theme , the same problem also exists.

**Comment by Jambo2018** [comment]
update to v0.1.9 and try again

**Comment by i-iooi-i** [comment]
> update to v0.1.9 and try again

![image](https://github.com/Jambo2018/notion-assistant-plugin/assets/1827701/44442968-909c-47f9-9c96-609a0f9636c8)
Cool, it worked successfully. Thank you. 🫡🫡🫡
