### ISSUE TITLE
  Option to enable/disable context menu on text selection (Re-add)

### ISSUE THREAD

**Issue by JwSh-1** [Jambo2018/notion-assistant-plugin#21]
When selecting text in the mobile version, a "contextual" menu appeared. That feature was removed in 0.2.6.

Could you please add it again, it was one of the functions that I used the most. 🙏

Perhaps a possible solution is to add a setting to activate or deactivate it as necessary.

**Comment by Jambo2018** [comment]
have a try [0.2.8](https://github.com/Jambo2018/notion-assistant-plugin/releases/tag/0.2.8)

**Comment by JwSh-1** [comment]
thank you 🙏
It works perfect
